### ISSUE TITLE
Grid Console returns 500

### ISSUE THREAD

**Issue by sailo888** [davehunt/flynnid#1]
Hey. Just informing you this works great until selenium 2.33+. Where they changed their UI for the console. When using Flyinnid to add the node to the grid, it'll still be successful but won't be able to hit the console (e.g. localhost:4444/grid/console). 

It'll return with a HTTP 500:
org.json.JSONObject$Null cannot be cast to java.lang.String

thank you.

timmy.

**Comment by davehunt** [comment]
Thanks for the issue report. Could you provide a full traceback? FlynnID shouldn't try to reach the console. It only uses /grid/register and the /grid/api/proxy?id=node_id so I'll need to know which one to fix.

**Comment by sailo888** [comment]
Hey! Thanks for getting back so quickly. 

Well, FlynnID is not trying to reach the console. It is when you open up the console to see your grid after the newly added node which in my case is android will cause the 500 response. 

This is the command I use to add the node is something like this:
flynnid --nodeport=8081 --nodehost={nodeurl} --browsername=android --platform=ANDROID --hubhost={hosturl} --hubport=4444

**Comment by davehunt** [comment]
Ahh, I think I understand. I'll look into this when I can. If you're interested in fixing it yourself, feel free to submit a pull request. Thanks again.

**Comment by sailo888** [comment]
Thank you! However, I am not really sure what is the problem :S

**Comment by davehunt** [comment]
It looks like you're missing the --browserver argument, try adding that and see if it works for you. I was able to get it to work with the latest version of FlynnID and Selenium Grid.
